require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.4.2'

target 'QLDT' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  #pod 'react-native-crypto-aes-cbc', :path => '../node_modules/react-native-crypto-aes-cbc'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'QLDTTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    # installer.pods_project.targets.each do |target|
    #   if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
    #     target.build_configurations.each do |config|
    #         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    #     end
    #   end
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    
  end
    
    # post_install do |installer|
    #   installer.pods_project.targets.each do |target|
    #     if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
    #       target.build_configurations.each do |config|
    #           config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    #       end
    #     end
   
    
  end
end

target 'QLDT-tvOS' do
  # Pods for QLDT-tvOS

  target 'QLDT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
